Repository witseie-elen4010/2023-group-lab-007, pull requests merged in 2023-05, with the labels that each got.

#44 Default student consultation list Developer Story
  _tests_/tests.spec.js
  package-lock.json
  package.json
  public/scripts/lecturer_dashboard.js
  public/scripts/student_dashboard.js
  src/routes/classRoutes.js
  src/studentConsultation.js
  src/views/student_dashboard.ejs
Labels: developer-sized-story

#51 Update sprint retrospective
  documentation/Conventions/StoryPointMatrix.JPG
  documentation/Sprints/Sprint_2/Week_2_User_Story_Map_Better_Quality.jpeg
  documentation/Sprints/Sprint_2/week_1_retrospective.md
Labels: documentation

#76 As a student create a booking at a selected time to meet the lecturer
  package.json
  public/scripts/student_dashboard.js
  src/routes/apiRoutes.js
  src/schemas/tablesSchemas.js
  src/views/student_dashboard.ejs
Labels: user-story

#77 View main consultation details
  public/scripts/lecturer_dashboard.js
  src/routes/apiRoutes.js
  src/services/consultation_service.js
  src/views/lecturer_dashboard.ejs
Labels: enhancement, user-story
